apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  project: livechat  
resources:
  - service.yaml
  - deployment.yaml
  - service-hl.yaml
images:
- name: nginx
  #newName: foo/bar1
  newTag: "1.15"
