apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonAnnotations:
  ver: "1.15"
# commonLabels:
#   someName: someValue
#   owner: alice
#   app: bingo
namePrefix: prod-
#namespace: prod
bases:
- ../../../base
images:
- name: nginx
  #newName: foo/bar1
  newTag: "1.15"
replicas:
- name: sl-demo-app
  count: 1
configMapGenerator:
- name: cm-demo-app
  literals:	
  - JAVA_HOME=/opt/java/jdk
  - JAVA_TOOL_OPTIONS=-agentlib:hprof 

# secretGenerator:
# - name: app-tls
#   files:
#   - secret/tls.cert
#   - secret/tls.key
#   type: "kubernetes.io/tls"
# - name: app-tls-namespaced
#   # you can define a namespace to generate
#   # a secret in, defaults to: "default"
#   namespace: apps
#   files:
#   - tls.crt=catsecret/tls.cert
#   - tls.key=secret/tls.key
#   type: "kubernetes.io/tls"
# - name: env_file_secret
#   envs:
#   - env.txt
#   type: Opaque