apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace:  argocd
resources:
- install.yaml
patchesStrategicMerge:
- patch-argocd-cm.yaml
- patch-secret.yaml
- patch-deployment.yaml
configMapGenerator:
- files:
  - ./files/private-key.txt
  name: private-keys
  behavior: create
generatorOptions:
  disableNameSuffixHash: true
  labels:
    kustomize.generated.resource: somevalue
  annotations:
    annotations.only.for.generated: othervalue