apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sl-demo-app
spec:
  template:
    spec:
      containers:
      - name: app
        env:
        - name: "DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: sl-demo-app
              key: db-password
        - name: "DB_USERNAME"
          valueFrom:
            secretKeyRef:
              name: sl-demo-app
              key: db-username