apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
- ../../../../base/servicea
replicas:
- name: sl-demo-app
  count: 1
patchesStrategicMerge:
- patch-deployment.yaml
- replica-and-rollout-strategy.yaml
- database-secret.yaml
secretGenerator:
- literals:
  - db-password=123456
  - db-username=root
  name: sl-demo-app
  type: Opaque
  #- name: env-file-secret
  #  envs:
  #- ./files/env.txt
  #type: Opaque
# - name: app-tls-namespaced
#   # you can define a namespace to generate
#   # a secret in, defaults to: "default"
#   namespace: apps
#   files:
#   - tls.crt=catsecret/tls.cert
#   - tls.key=secret/tls.key
#   type: "kubernetes.io/tls"  
configMapGenerator:
- files:
  - ./files/otter.properties
  name: cm-demo-app
  behavior: create
generators:
- config-sops-generator.yaml
