apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sl-demo-app
spec:
  template:
    spec:
     containers:
     - name: app
       env:
       - name: CUSTOM_ENV_VARIABLE
         value: helloworld
